name: Deploy Backend to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to GCP VM
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@<your-gcp-external-ip> << 'EOF'
            cd CraftConnect/backend
            git pull origin main
            npm install
            pm2 restart all || pm2 start server.js --name craftconnect-backend
          EOF
