name: Deploy Backend to GCP

on:
  push:
    branches:
      - main  # Deploys when code is pushed to 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.GCP_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.GCP_VM_IP }} >> ~/.ssh/known_hosts

    - name: Deploy to GCP
      run: |
        ssh ubuntu@${{ secrets.GCP_VM_IP }} << 'EOF'
        set -e  # Exit on error

        # Update VM and install dependencies
        sudo apt update && sudo apt upgrade -y
        sudo apt install -y nodejs npm git pm2

        # Navigate to project directory
        cd ~/CraftConnect || git clone https://github.com/Epics-111/CraftConnect.git ~/CraftConnect
        cd ~/CraftConnect/backend

        # Pull latest changes
        git reset --hard
        git pull origin main

        # Install dependencies
        npm install

        # Set up environment variables
        echo "PORT=5000" > .env
        echo "MONGO_URI=mongodb+srv://yourUser:yourPassword@cluster.mongodb.net/CraftConnect?retryWrites=true&w=majority" >> .env
        echo "JWT_SECRET=your_jwt_secret" >> .env
        echo "GEMINI_API_KEY=your_gemini_api_key" >> .env
        echo "REACT_FRONTEND_URL=http://your-vm-external-ip:3000" >> .env

        # Restart backend using PM2
        pm2 delete craftconnect-backend || true
        pm2 start server.js --name craftconnect-backend
        pm2 save

        # Open firewall ports
        sudo ufw allow 22
        sudo ufw allow 5000
        sudo ufw enable

        echo "Deployment Completed Successfully!"
        EOF
