name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Change this if deploying from a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup SSH Key and Connect to EC2
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > projectkeypair.pem
        chmod 400 projectkeypair.pem

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i projectkeypair.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ec2-user/CraftConnect  # Amazon Linux uses ec2-user
          git pull origin main
          npm install  # If it's a Node.js project
          pm2 restart all  # Restart the app if using PM2
          exit
        EOF

