name: Deploy CraftConnect to AWS EC2 (Amazon Linux)

on:
  push:
    branches:
      - main  # Change this if deploying from a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH Key and Known Hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy Code to Amazon Linux EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e  # Exit immediately if a command fails

            # Navigate to project directory or clone if not exists
            if [ ! -d "/home/ec2-user/CraftConnect" ]; then
              git clone https://github.com/Epics-111/CraftConnect.git /home/ec2-user/CraftConnect
            fi
            
            cd /home/ec2-user/CraftConnect

            # Pull latest changes
            git reset --hard
            git pull origin main

            # Install dependencies for backend
            cd backend
            npm install
            pm2 restart backend || pm2 start server.js --name backend

            # Install dependencies for frontend
            cd ../frontend
            npm install
            npm run build  # Build frontend
            pm2 restart frontend || pm2 serve build 3000 --name frontend

            echo "Deployment successful!"
          EOF
