name: Deploy Backend to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > ~/.ssh/aws_key.pem
          chmod 600 ~/.ssh/aws_key.pem
          ssh-keyscan -H 13.203.159.186 >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/aws_key.pem

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/aws_key.pem -o StrictHostKeyChecking=no ubuntu@13.203.159.186 << 'EOF'
            cd ~/CraftConnect/backend
            git pull origin main
            npm install
            pm2 restart server
          EOF

 
