name: Deploy Backend to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/private_key.pem
          chmod 600 ~/.ssh/private_key.pem

      - name: Disable Host Key Checking
        run: echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Deploy Backend to EC2
        run: |
          scp -i ~/.ssh/private_key.pem -r backend ubuntu@${{ secrets.EC2_PUBLIC_IP }}:~/backend
          ssh -i ~/.ssh/private_key.pem ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            cd ~/backend
            npm install
            pm2 stop all || true
            pm2 start server.js --name craftconnect-backend
          EOF

